on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          mkdir -p build/outputs/release
          echo hello > build/outputs/release/hello.txt
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: build/outputs/release/hello.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
